config/routes.rb
Msgs::Application.routes.draw do
  resources :friendships
  resources :messages
  resources :user_conversations, :controller => "user_conversations" do
    resources :messages
    member do
      post :mark_as_read
      post :mark_as_unread
      post :user_conversations
    end
  end
  post "user_conversations/:user_conversation_id/messages(.:format)" => "messages#create", as: "create_message" 
  get "users", to: "users#index"
  
  root "users#index"
  devise_for :users
  get "users/search", to: "users#search", as: "users_search"
  get "users/roles", to: "users#roles", as: "users_roles"
  
  devise_scope :user do 
    get "sign_in", to: "devise/sessions#new"
    post "sign_in", to: "devise/sessions#create"
    get "sign_up", to: "devise/registrations#new"
    post "sign_up", to: "devise/registrations#create"
    get "sign_out", to: "devise/sessions#destroy"
  end

  get "friends", to: "friendships#index"
  post "friends", to: "friendships#destroy"
  get "friends/delete_request", to: "friendships#delete_friend_request"
  get "friends/accept_request", to: "friendships#accept_friend_request"

  #url like site.com/username
  get ":user_name", to: "users#show", as: "user_profile"

  scope ":user_name" do
      get '', to: 'users#show'
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
 	belongs_to :user
 	belongs_to :friend, class_name: "User"
 	belongs_to :friend_inverse, class_name: "User", foreign_key: "friend_id"

 	def self.count_friends(user_id, type='all')
 		user = User.find(user_id) || not_found
 		if type == 'online'
	 		user.friends.each do |friend|
	 			online_friends = []
	 			online_friends << friend if friend.last_request_at > 5.minutes.ago 
	 			return online_friends.count
	 		end
 		else
 			user.friends.count
 		end
 	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authenticate_user! 
  
  def index 
    @user = current_user
    if params[:section] == 'requests'
      @requests = current_user.friends_requests
      render("requests", requests: @requests)
    else
      @friends = @user.friendships
    end

    @conversation = @user.user_conversations.build
    @conversation.build_conversation.messages.build
  end

  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      redirect_to root_url, :notice => "Added friend."
    else
      redirect_to users_path, :notice => 'Unable to add friend'
    end
  end

  def accept_friend_request
      @current_request = Friendship.where(user_id: params[:request_user_id], friend_id: current_user.id)
      @current_request.first.update_attributes confirmed: true
      
      @new_friendship = Friendship.new(user_id: current_user[:id], friend_id: params[:request_user_id], confirmed: true)
      if @new_friendship.save
        redirect_to friends_path, notice: "Friends request accepted"
      else
        redirect_to friends_path, notice: "Friends request was'nt accepted"
      end
  end

  def delete_friend_request
      @current_request = Friendship.find_by_user_id_and_friend_id(params[:request_user_id], current_user[:id])
      @current_request.destroy
      redirect_to friends_path, notice: "Request deleted"
  end


  def destroy
    @friendship_current = current_user.friendships.find(params[:id])
    @friendship_friend = Friendship.find_by_user_id_and_friend_id(@friendship_current.friend_id, current_user[:id])
    @friendship_current.destroy
    @friendship_friend.destroy
    redirect_to root_url, :notice => "Friend was removed"
  end

  def count_of_friends_requests
    current_user.friends_requests.count 
  end

  private 

  def friendship_params
    params.requare(:friendship).permit(:user_id, :friend_id, :confirmed)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper

	def get_text_of_empty_list
		if params[:section] == 'online' then "No online friends"
		else "No friends yet" end 
	end

end

app/views/friendships/index.html.erb
<%= render "friendships/shared/nav" %>
<div class="span9">
<h2>My friends</h2>
<% if count_of_friends(current_user[:id]) != 0 %>
  <table class='users-list-wrap'>
      <% for friendship in @friends %>
        <% if friendship.confirmed? %>
          <% if !check_user_status(friendship.friend.id, true) and params[:section] == 'online' %>
            <% break %>
          <% end %>
          <tr class='users-current-user'>
            <td class='users-image-field'>
              <%= image_tag friendship.friend.avatar.url(:thumb) %>
            </td>
            <td class='users-name-field'>
              <%= link_to friendship.friend.name, user_profile_path(friendship.friend.user_name) %><br>
              <span class="user-status"><%= check_user_status(friendship.friend.id) %></span>
            </td>
            <td class='users-controls-field'>
              <%= link_to "Send a message", '#message_model', :class => 'message-link', "data-toggle" => "modal", 
                      "user_id" => "#{friendship.friend.id}", "user_name" => "#{friendship.friend.name}"  %>
              <br><%= link_to "Remove friend", friendship, :method => :delete, confirm: "Are you sure?" %>
            </td>
          </tr>
        
      <% end %> 
    <% end %>
  </table>    
<% else %>
  <span class="empty-list"><%= get_text_of_empty_list %></span>
<% end %>
</div>

<%= render "friendships/shared/new_message", conversation: @conversation, friends: @friends %>

app/views/friendships/requests.html.erb
<div class="row"><%= link_to "All friends", friends_path %></div>
<div class="row">
	<table class='users-list-wrap'>
	  	<% @requests.each do |user| %>
	  	<tr class='users-current-user'>
			<td class='users-image-field'><%= image_tag user.avatar.url(:thumb) %></td>
			<td class='users-name-field'><%= link_to user.name, user_profile_path(user.user_name) %>
				<br><span class="user-status"><%= check_user_status(user.id) %></span>
			</td>
			<td class='users-controls-field'>
				<%= link_to "Accept", friends_accept_request_path(request_user_id: user.id), 
						class: "btn btn-info btn-small" %>
				<%= link_to "Delete", friends_delete_request_path(request_user_id: user.id), 
						class: "btn btn-small" %>

			</td>
		</tr>
		<% end %>
	</table>		
</div>