config/routes.rb
Msgs::Application.routes.draw do
  resources :friendships
  resources :messages
  resources :user_conversations, :controller => "user_conversations" do
    resources :messages
    member do
      post :mark_as_read
      post :mark_as_unread
      post :user_conversations
    end
  end
  post "user_conversations/:user_conversation_id/messages(.:format)" => "messages#create", as: "create_message" 
  get "users", to: "users#index"
  
  root "users#index"
  devise_for :users
  get "users/search", to: "users#search", as: "users_search"
  get "users/roles", to: "users#roles", as: "users_roles"
  
  devise_scope :user do 
    get "sign_in", to: "devise/sessions#new"
    post "sign_in", to: "devise/sessions#create"
    get "sign_up", to: "devise/registrations#new"
    post "sign_up", to: "devise/registrations#create"
    get "sign_out", to: "devise/sessions#destroy"
  end

  get "friends", to: "friendships#index"
  post "friends", to: "friendships#destroy"
  get "friends/delete_request", to: "friendships#delete_friend_request"
  get "friends/accept_request", to: "friendships#accept_friend_request"

  #url like site.com/username
  get ":user_name", to: "users#show", as: "user_profile"

  scope ":user_name" do
      get '', to: 'users#show'
  end

end

app/models/user_conversation.rb
class UserConversation < ActiveRecord::Base
	belongs_to :user
	belongs_to :conversation
	has_many :messages, through: :conversation, dependent: :destroy
	attr_accessor :to
	accepts_nested_attributes_for :conversation, allow_destroy: true


	delegate :subject, to: :conversation
	delegate :users, to: :conversation

	#before_create :create_user_conversations
	
	#def check_messages(user_id)
	#	messages = Message.unread_messages(self.id, user_id)
	#	self.update_attributes read: true unless self.read?
	#	messages.each {|m| m.update_attributes read: true unless m.read?}
	#end

	private

	  def create_user_conversations
	   #return if to.blank?
	  	
	   for recip in to
	     UserConversation.create :user_id => recip, :conversation => conversation
	    end
	  end



end

app/controllers/user_conversations_controller.rb
class UserConversationsController < ApplicationController
	before_filter :authenticate_user!
	before_action :set_conversation, only: [:show, :edit, :update, :destroy]

	def index 
		@user = User.includes(:user_conversations).find(current_user)
		@conversations = @user.user_conversations.order('last_message_at DESC')
	end

	def show 
		@conversation = UserConversation.find(params[:id]) 
		check_messages(@conversation)
		@message = Message.new(conversation_id: @conversation.conversation_id, user_id: current_user[:id])
		redirect_to user_conversation_path if @conversation.deleted?
		
		respond_to do |format|
			format.html
			format.js 
		end
	end

	def new 
		@user = User.includes(:friendships).find(current_user)
		@friends = @user.friendships
		@conversation = @user.user_conversations.build
		@conversation.build_conversation.messages.build
	end

	def create 
		@conversation = UserConversation.new(user_conversation_params)
		@conversation.user = current_user
		@conversation.conversation.messages.first.user = current_user
		@conversation.conversation.between = @conversation.to.dup
		@conversation.conversation.between << current_user[:id]
		@conversation.save!
		
		if !@conversation.to.blank?
			@conversation.to.each { |t| UserConversation.create user_id: t, conversation: @conversation.conversation }
		end

		redirect_to user_conversation_path(@conversation)
	end

	def destroy
		@conversation = UserConversation.find(params[:id])
		@conversation.update_attributes deleted: true
		@conversations = User.find(current_user).user_conversations

		respond_to do |format|
			format.js {@conversations}
		end
	end

	def check_messages(conversation)
		messages = Message.where(conversation_id: conversation.conversation_id).where("user_id <> ?", current_user[:id]).where(read: false)
		conversation.update_attributes read: true unless conversation.read?
		
		messages.each {|m| m.update_attributes read: true unless m.read?}
	end

	#if exsist some conversation between current users, then method returns this conversations id
	def check_conversation(between_users)
		@current_user_conversations = UserConversation.select(:conversation_id).where(user_id: current_user[:id])
		@current_user_conversations.each do |con|	
			return con.id if con.between.sort == between_users.sort
		end
		return false
	end

	private 

	def set_conversation
		@conversation = UserConversation.find(params[:id])
	end

	def user_conversation_params
		params.require(:user_conversation).permit(:deleted, :user_id, :conversation_id, :read, to: [],
			conversation_attributes: [:id, :subject, messages_attributes: [:id, :body, :user_id, :conversation_id]])
	end

end

app/helpers/user_conversations_helper.rb
module UserConversationsHelper

	def check_read_status(conversation)
		if conversation.read != nil and  conversation.read == false
			return "unread"
		end
	end
end

app/views/user_conversations/_conversations.html.erb
<div class="list-group" id="conversatinons-list">
  <% for conversation in conversations do %>
    <% if !conversation.deleted? %>
        <div class="list-group-item <%= check_read_status(conversation) %> ">
            <% if can? :destroy, UserConversation %>
                <%= link_to 'delete', user_conversation_path(conversation), method: :delete, 
                    class: "pull-right delete-con", remote: true, confirm: "are you sure?"  %>
            <% end %>
            <%= link_to user_conversation_path(conversation) do %>
            	    <h4 class="list-group-item-heading msg-head"><%= conversation.subject %></h4>
            	    <p class="list-group-item-text">
            	    	<strong> 
            	    		<%= conversation.messages.last.user.name %>
            	    	</strong>
            	    	: <span class="msg-body"><%= conversation.messages.last.body %></span><br>
                          <span class="msg-time con-msg-time">
                            <%= time_ago_in_words(conversation.messages.last.created_at) %> ago.
                          </span>
            	    </p>
            <% end %>
        </div>
    <% end %>
  <% end %>
</div>

app/views/user_conversations/check.js.erb
$("#messages-area").html("<%=j render messages/messages, messages: @messages %>");

app/views/user_conversations/destroy.js.erb
$("#conversatinons-list").html("<%=j render 'conversations', conversations: @conversations %>")

app/views/user_conversations/index.html.erb
<h4><%= @user.name %>'s Conversations</h4>
<div id="conversations-list-wrap">
    <%= render "conversations", conversations: @conversations %>
</div>
<br>
<div class="row-fluid">
    <%= link_to "Create a New Conversation", new_user_conversation_path(@user), class: "btn btn-primary" %>
</div>

app/views/user_conversations/new.html.erb
<h4>New Conversation</h4>


<%= form_for(@conversation) do |f| %>
  <div>
    <%= f.label :to %><br />
      <select multiple class="form-control" id="friends_list" name="user_conversation[to][]">
        <% for user in @friends %>
          <option value="<%= user.friend.id %>"><%= user.friend.name %></option>
        <% end %>
      </select>
    <br>
  </div>
  <%= f.fields_for :conversation do |c| %>
    <div>
      <%= c.label :subject %>
      <%= c.text_field :subject %>
    </div>
    <%= c.fields_for :messages do |m| %>
      <div>
        <%= m.label :body %><br />
        <%= m.text_area :body %>
      </div>
    <% end %>
  <% end %>

  <%= f.submit "Create conversation", class: "btn btn-primary" %>
<% end %>

app/views/user_conversations/show.html.erb
<h1><%= @conversation.subject %></h1>
<div class="row">
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
            Users in this conversation
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse">
        <div class="panel-body">
          <%= render "messages/members", conversation: @conversation %>
        </div>
      </div>
    </div>
  </div>
</div><br>
<div class="row">
  <div class="span9">
  <div class="media-list" id="messages-area">
    <%= render "messages/messages", messages: @conversation.messages.limit(25) %>
  </div>
  <%= render "messages/write", message: @message %>
</div>
</div>

<%= link_to "Back to conversations", user_conversations_path(@user) %>

app/views/user_conversations/show.js.erb
setInterval(function(){
	$('#messages-area').html("<%=j render "messages/messages", messages: @messages %>");
}, 3000);